resolve tasks 8 (auth)
js-tasks-ru/nodejs-20210513_insomnia7 pull request #9
Opened 2021-06-18 11:21 UTC by AlexeyMart

resolve tasks 8 (auth)

2021-06-18 11:22 UTC, jsru commented
Добавляю преподавателя (@RidgeA) для код-ревью.

2021-06-23 07:12 UTC, RidgeA requested changes

2021-06-23 07:12 UTC, RidgeA commented on 08-authentication/02-oauth/config.js
> +      app_id: process.env.GITHUB_APP_ID || '6df9452b5bf9fea6e356',
не публикуйте пароли, ключи и т.п. в систему контроля версий.

2021-06-26 06:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-26 06:09 UTC, jsru commented
Добавляю преподавателя (@RidgeA) для код-ревью.

2021-06-27 10:59 UTC, RidgeA approved these changes

2021-06-27 11:00 UTC, merged